<a href="https://colab.research.google.com/github/uditsaurabh/APIandDynamoCourse/blob/lesson4/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensor initialization.
How to create a tensor?
device attribute defiens what kind of device we will be using for this tensor operstions..

RuntimeError                              Traceback (most recent call last)
<ipython-input-7-c988eb3ca81b> in <cell line: 2>()
      1 import torch
----> 2 my_tensor = torch.tensor([[1,2,3],[4,5,6]],dtype = torch.float64,device='gpu')

RuntimeError: Expected one of cpu, cuda, ipu, xpu, mkldnn, opengl, opencl, ideep, hip, ve, fpga, ort, xla, lazy, vulkan, mps, meta, hpu, mtia, privateuseone device type at start of device string: gpu

Required ggrad will be used tocomputev the gradient.

In [2]:
import torch

device = 'cuda' if torch.cuda.is_available() else "cpu"
# Set default dtype to torch.double
torch.set_default_dtype(torch.double)

my_tensor = torch.tensor([[],[]],dtype = torch.double,device=device,requires_grad=True)

In [3]:
my_tensor

tensor([], size=(2, 0), requires_grad=True)

In [4]:
my_tensor.dtype

torch.float64

In [5]:
double_tensor = torch.empty(3, dtype=torch.double)
print(double_tensor.dtype)  # Output: torch.float64 (double)

double_tensor_zeros = torch.zeros(2, 2, dtype=torch.double)
print(double_tensor_zeros.dtype)  # Output: torch.float64 (double)

torch.float64
torch.float64


In [6]:
float_tensor = torch.tensor([3.0, 4.0])
double_tensor = float_tensor.double()
print(double_tensor.dtype)

torch.float64


In [7]:
# shows the device
print(double_tensor.device)

cpu


Other common methods to intialize the tensors

In [12]:
x = torch.empty(size = (3,3))
x

tensor([[4.6493e-310, 5.3028e+180,  6.0074e-67],
        [ 4.7402e+97,  6.7609e-67, 4.2672e+126],
        [4.2522e+180, 7.4854e+247, 2.3236e+251]])

In [13]:
y = torch.zeros(size = (2,4))
y

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
z = torch.rand(size=(3,4))
z

tensor([[0.5677, 0.3108, 0.5167, 0.8517],
        [0.7111, 0.5068, 0.7982, 0.0155],
        [0.5202, 0.7887, 0.5268, 0.7535]])

In [17]:
a = torch.ones(size=(3,3))
b = torch.eye(3,3)
(a,b)

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]))

In [19]:
x =torch.arange(start=0,end=15,step=3)
x

tensor([ 0,  3,  6,  9, 12])

In [21]:
l = torch.linspace(start=0,end=10,steps=100)
l

tensor([ 0.0000,  0.1010,  0.2020,  0.3030,  0.4040,  0.5051,  0.6061,  0.7071,
         0.8081,  0.9091,  1.0101,  1.1111,  1.2121,  1.3131,  1.4141,  1.5152,
         1.6162,  1.7172,  1.8182,  1.9192,  2.0202,  2.1212,  2.2222,  2.3232,
         2.4242,  2.5253,  2.6263,  2.7273,  2.8283,  2.9293,  3.0303,  3.1313,
         3.2323,  3.3333,  3.4343,  3.5354,  3.6364,  3.7374,  3.8384,  3.9394,
         4.0404,  4.1414,  4.2424,  4.3434,  4.4444,  4.5455,  4.6465,  4.7475,
         4.8485,  4.9495,  5.0505,  5.1515,  5.2525,  5.3535,  5.4545,  5.5556,
         5.6566,  5.7576,  5.8586,  5.9596,  6.0606,  6.1616,  6.2626,  6.3636,
         6.4646,  6.5657,  6.6667,  6.7677,  6.8687,  6.9697,  7.0707,  7.1717,
         7.2727,  7.3737,  7.4747,  7.5758,  7.6768,  7.7778,  7.8788,  7.9798,
         8.0808,  8.1818,  8.2828,  8.3838,  8.4848,  8.5859,  8.6869,  8.7879,
         8.8889,  8.9899,  9.0909,  9.1919,  9.2929,  9.3939,  9.4949,  9.5960,
         9.6970,  9.7980,  9.8990, 10.00

mean and std

In [24]:
n = torch.empty(size=(1,10)).normal_(mean=0,std=.5)
n

tensor([[ 0.4110, -0.7539,  0.1744,  0.3589,  0.2445,  0.0525,  0.4148, -0.5668,
          1.0330, -0.4843]])

In [26]:
d =torch.empty(size=(1,10)).uniform_(0,1)
d

tensor([[0.7784, 0.1091, 0.8575, 0.4625, 0.0706, 0.7562, 0.3783, 0.3036, 0.4683,
         0.6876]])

In [30]:
o = torch.diag(torch.ones(5))
o

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

How to intialize the tensors to the different types